Step2
zunior-team/java-lotto pull request #3
Opened 2020-05-20 01:45 UTC by nokchax

2020-05-20 05:45 UTC, gale34 commented on src/main/java/lotto/prize/LottoPrize.java
> +    NONE(0, 0);
Java 7부터는 `2_000_000_000`처럼 숫자에 밑줄을 사용해서 가독성을 높일 수 있습니다!

2020-05-20 05:45 UTC, gale34 commented on src/main/java/lotto/number/LottoNumbers.java
> +    private final List<LottoNumber> lottoNumbers;
아예 lottoNumbers를 Set으로 관리하는 건 어떻게 생각하시나요??

2020-05-20 05:46 UTC, gale34 commented on src/main/java/lotto/number/LottoNumber.java
> +    public static LottoNumber of(final int number) {
LottoNumber는 1부터 45까지의 범위가 명확해서, 만들어지는 경우가 한정적일 것 같은데요.
이 객체는 불변객체로 보이는데, 매번 새로운 불변 인스턴스를 만드는 구조일 것 같습니다.
캐시해서 사용해 볼 수는 없을까요??

2020-05-20 05:46 UTC, gale34 commented on src/main/java/lotto/lotto/LottoSeller.java
> +    private static List<LottoTicket> buyAutoLotto(final int payment) {
```suggestion
    private static List<LottoTicket> buyAutoLottoTickets(final int payment) {
```
Lotto라는 이름의 클래스가 존재해서, 명확히 구별하는게 좋을 것 같아요

2020-05-20 05:48 UTC, gale34 commented on src/main/java/lotto/view/ConsoleOutput.java
> +        return Arrays.copyOf(lottoPrizes, lottoPrizes.length - 1);
LottoPrize.NONE을 뺀 LottoPrize[]를 얻기 위한 과정이라면, LottoPrize에 static 메소드를 하나 만들어도 좋을 것 같습니다!

2020-05-20 05:49 UTC, gale34 commented on src/main/java/lotto/view/ConsoleOutput.java
> +    }
수익률을 계산하는 책임도 MatchResult에 위임하는건 어떨까요?? view layer에 비즈니스 로직이 포함된 느낌이 듭니다.

2020-05-20 05:50 UTC, gale34 commented on src/main/java/lotto/view/ConsoleOutput.java
> +                .forEach(System.out::println);
음..LottoTicketDto의 toString()을 재정의하는 방법에 대해선 어떻게 생각하시나요?

2020-05-20 05:52 UTC, gale34 commented on src/test/java/lotto/lotto/LottoSellerTest.java
> +}
잘못된 인자가 들어갔을때, 예외 케이스에 대한 테스트 코드가 필요해보입니다!

2020-05-20 05:57 UTC, gale34 commented on src/test/java/lotto/lotto/LottoTest.java
> +        long sum = Arrays.stream(LottoPrize.values())
매칭된 로또 카운트의 합이므로, 변수 명을 조금 더 명확하게 하는건 어떨까요???
당첨금의 합으로 오인할 수도 있을 것 같습니다!

2020-05-20 06:00 UTC, gale34 requested changes
수고하셨습니다! 로또 부터는 객체와 테스트 코드가 많아지니까 리뷰 시간이 오래 걸리는군요...
다음 단계로 넘어가기전에 몇 가지 확인해주셨으면 하는 코멘트들이 있습니다!
천천히 반영해주세요:)

2020-05-20 06:02 UTC, nokchax commented on src/main/java/lotto/prize/LottoPrize.java
> +    NONE(0, 0);
오 처음알았네요 감사합니다

2020-05-20 06:03 UTC, nokchax commented on src/main/java/lotto/number/LottoNumbers.java
> +    private final List<LottoNumber> lottoNumbers;
그것도 좋은 방법인거 같은데 음 그러면 LinkedHashSet을 사용해야겠네요, 한번 적용해볼게요

2020-05-20 06:03 UTC, nokchax commented on src/main/java/lotto/number/LottoNumber.java
> +    public static LottoNumber of(final int number) {
오 좋은 생각입니다

2020-05-20 06:04 UTC, nokchax commented on src/main/java/lotto/lotto/LottoSeller.java
> +    private static List<LottoTicket> buyAutoLotto(final int payment) {
넵 수정해야겠네요

2020-05-20 06:04 UTC, nokchax commented on src/main/java/lotto/view/ConsoleOutput.java
> +        return Arrays.copyOf(lottoPrizes, lottoPrizes.length - 1);
그럴까 하다가 말았는데 흠 옮겨볼까요

2020-05-20 06:09 UTC, nokchax commented on src/main/java/lotto/view/ConsoleOutput.java
> +    }
저도 고민하다가 match result는 일종의 dto라고 생각해서 비지니스 로직을 뺐는데 그게 나을까요? 어떻게 생각하세요?

2020-05-20 06:11 UTC, nokchax commented on src/main/java/lotto/view/ConsoleOutput.java
> +    }
`일반적인 DTO는 로직을 갖고 있지 않는 순수한 데이터 객체이며 속성과 그 속성에 접근하기 위한 getter, setter 메소드만 가진 클래스를 말합니다`

2020-05-20 06:12 UTC, nokchax commented on src/main/java/lotto/view/ConsoleOutput.java
> +                .forEach(System.out::println);
이것도 위랑 같은 맥락에서 뺐는데, toString은 로직이라고 볼수 없으려나 흠...
이것도 논의해보고 싶긴하네요

2020-05-20 06:12 UTC, nokchax commented on src/main/java/lotto/view/ConsoleOutput.java
> +                .forEach(System.out::println);
다른 리뷰어 분들은 어떻게 생각하시나요?

2020-05-20 06:13 UTC, nokchax commented on src/test/java/lotto/lotto/LottoTest.java
> +        long sum = Arrays.stream(LottoPrize.values())
네 그래야겠네요 ㅎㅎ

2020-05-20 06:14 UTC, nokchax commented on src/test/java/lotto/lotto/LottoSellerTest.java
> +}
앗 빠져있네요, 추가해두겠습니다

2020-05-20 06:17 UTC, gale34 commented on src/main/java/lotto/number/LottoNumbers.java
> +    private final List<LottoNumber> lottoNumbers;
그냥 HashSet쓰고 List<Integer>로 반환할때만 정렬 한번 해줘도 될것 같아요:)

2020-05-20 06:21 UTC, gale34 commented on src/main/java/lotto/view/ConsoleOutput.java
> +    }
아 패키지가 DTO로 있군요...음 제 생각엔 객체로 간주해도 무방할 것 같은데요.
지금 쓰이는 getter나 setter라곤 getPayment()뿐인데, 비즈니스 로직에서 사용하는건 이 코멘트에 포함된 부분이라, 메소드를 따로 빼면 여기선 안써도 될것같고, 
테스트코드에서 사용하는건, 예상 객체를 하나 만들어서 객체간의 비교로 하면 getter도 없앨 수 있을 것 같습니다.

2020-05-20 06:23 UTC, gale34 commented on src/main/java/lotto/view/ConsoleOutput.java
> +                .forEach(System.out::println);
dto로 다룰건지 객체로 다룰건진, 개개인 코드마다 달라서...명확한 기준은 없었어요. 아직까진 이부분에 대한 리뷰어끼리 논의는 없었네요 ㅠㅠ
MatchResult를 DTO로 생각하신 이유가 있을까요???

2020-05-21 10:48 UTC, nokchax commented
개인적으로는 toString을 오버라이딩해서 안쓰는게 좋다고 생각하는데요.
예를 들어서 이번에 toString을 오버라이딩 해서 아래처럼 출력을 한다고 가정해볼게요
x개 일치 (y원) - z개

그런데 다음과 같이 웹환경에서 테이블 형식으로 결과를 보여주는 방식으로 변경된다면?
|일치|당첨금|개수|
|---|---|---|
|3개 일치|5000원|1개|
|4개 일치|50000원|1개|
|5개 일치|15000000원|0개|
|6개 일치|2000000000원|1개|

총 수익률은 ..%입니다

LottoPrizeResult 객체의 toString을 더이상 사용하지 않게 되고, 뷰를 위해서 추가적인 getter를 사용하게 될거같아요 따라서 toString을 사용하면 View 환경에 따라 도메인에 변경이 생기게 되는 구조인거 같아요. 그래서 toString을 통한 view 생성 보다는 DTO사용이 나을거 같아요..

2020-05-24 03:29 UTC, gale34 commented on src/main/java/lotto/lotto/Lotto.java
> +        if (lottoTickets == null) {
전 잘 사용안하는 편이긴 한데, 몇몇 리뷰어분들은 가독성을 위해서 `Objects.isNull()` 사용을 권장하시더라구요. 참고해보셨으면 좋겠습니다!

2020-05-24 03:34 UTC, gale34 approved these changes
수고하셨습니다 !!!

2020-05-24 03:35 UTC, merged