restore : step4 code
zunior-team/java-lotto pull request #6
Opened 2020-05-25 12:56 UTC by nokchax

브랜치가 꼬여서 커밋이 몰아졌네요 ㅋㅋ

git checkout step4
git rebase --onto nokchax HEAD~1

2020-05-25 23:46 UTC, gale34 commented on src/main/java/lotto/lotto/LottoSeller.java
> +        LottoTickets autoTickets = LottoTickets.init(buyAutoLottoTickets(paymentInfo.getPayment()));
payment에서 살 수 있는 만큼 자동 로또를 구입하는 것 같은데, 수동 로또를 구매하고 남은 금액으로 사야하지 않을까요???

2020-05-25 23:58 UTC, gale34 commented on src/test/java/lotto/money/PaymentInfoTest.java
> +
수동 로또 번호를 7개 집어넣으면 어떻게 되나요??
LottoNumbers validate()에서는 6보다 작은 경우만 체크하는 것 같아서요
물론 LottoNumbers에 관한 테스트라 여기서 할 건 아닌 듯 하지만...지난번 피드백에서 빠뜨렸네요..

2020-05-26 00:00 UTC, gale34 requested changes
수고하셨습니다!
로직 구현에 관한 몇 가지 코멘트를 달았습니당

2020-05-26 00:38 UTC, nokchax commented on src/main/java/lotto/lotto/LottoSeller.java
> +        LottoTickets autoTickets = LottoTickets.init(buyAutoLottoTickets(paymentInfo.getPayment()));
앗 ㅋㅋㅋ 그렇네요

2020-05-26 00:38 UTC, nokchax commented on src/test/java/lotto/money/PaymentInfoTest.java
> +
수정하겠읍니다

2020-05-26 00:45 UTC, gale34 approved these changes
수고하셨습니다. 이제 사다리만...

2020-05-26 00:45 UTC, merged